version: "3.8"

services:
  # Servidores (3 servidores)
  server1:
    image: server:latest
    container_name: server1
    privileged: true  
    networks:
      servers:
        ipv4_address: 10.0.11.10
    ports:
      - "5001:5001"
    restart: on-failure

  server2:
    image: server:latest
    container_name: server2
    privileged: true  
    networks:
      servers:
        ipv4_address: 10.0.11.11
    ports:
      - "5002:5001"
    restart: on-failure

  server3:
    image: server:latest
    container_name: server3
    privileged: true  
    networks:
      servers:
        ipv4_address: 10.0.11.12
    ports:
      - "5003:5001"
    restart: on-failure

  # Clientes (3 clientes)
  client1:
    image: client:latest
    container_name: client1
    privileged: true  
    networks:
      clients: {}
    ports:
      - "8501:8501"
    restart: on-failure

  client2:
    image: client:latest
    container_name: client2
    privileged: true  
    networks:
      clients: {}
    ports:
      - "8502:8501"
    restart: on-failure

  client3:
    image: client:latest
    container_name: client3
    privileged: true  
    networks:
      clients: {}
    ports:
      - "8503:8501"
    restart: on-failure

networks:
  servers:
    external: true
    name: servers

  clients:
    name: clients
    external: true
