# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/proto/message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server/proto/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.proto import models_pb2 as server_dot_proto_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aserver/proto/message.proto\x12\x06tweety\x1a\x19server/proto/models.proto\"7\n\x12PostMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"7\n\x13PostMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x12GetMessagesRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"8\n\x13GetMessagesResponse\x12!\n\x08messages\x18\x01 \x03(\x0b\x32\x0f.tweety.Message\"H\n\x14RepostMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1e\n\x16original_message_index\x18\x02 \x01(\x05\"9\n\x15RepostMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xee\x01\n\x0eMessageService\x12\x46\n\x0bPostMessage\x12\x1a.tweety.PostMessageRequest\x1a\x1b.tweety.PostMessageResponse\x12\x46\n\x0bGetMessages\x12\x1a.tweety.GetMessagesRequest\x1a\x1b.tweety.GetMessagesResponse\x12L\n\rRepostMessage\x12\x1c.tweety.RepostMessageRequest\x1a\x1d.tweety.RepostMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.proto.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTMESSAGEREQUEST']._serialized_start=65
  _globals['_POSTMESSAGEREQUEST']._serialized_end=120
  _globals['_POSTMESSAGERESPONSE']._serialized_start=122
  _globals['_POSTMESSAGERESPONSE']._serialized_end=177
  _globals['_GETMESSAGESREQUEST']._serialized_start=179
  _globals['_GETMESSAGESREQUEST']._serialized_end=217
  _globals['_GETMESSAGESRESPONSE']._serialized_start=219
  _globals['_GETMESSAGESRESPONSE']._serialized_end=275
  _globals['_REPOSTMESSAGEREQUEST']._serialized_start=277
  _globals['_REPOSTMESSAGEREQUEST']._serialized_end=349
  _globals['_REPOSTMESSAGERESPONSE']._serialized_start=351
  _globals['_REPOSTMESSAGERESPONSE']._serialized_end=408
  _globals['_MESSAGESERVICE']._serialized_start=411
  _globals['_MESSAGESERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
