# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodels.proto\x12\x06tweety\"\xc8\x01\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x11\n\tis_repost\x18\x05 \x01(\x08\x12\x1b\n\x13original_message_id\x18\x06 \x01(\t\x12 \n\x18original_message_user_id\x18\x07 \x01(\t\x12\"\n\x1aoriginal_message_timestamp\x18\x08 \x01(\t\"K\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rpassword_hash\x18\x04 \x01(\t\"#\n\x0cUserMessages\x12\x13\n\x0bmessage_ids\x18\x01 \x03(\t\"\'\n\rUserFollowing\x12\x16\n\x0e\x66ollowing_list\x18\x01 \x03(\t\"\'\n\rUserFollowers\x12\x16\n\x0e\x66ollowers_list\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=25
  _globals['_MESSAGE']._serialized_end=225
  _globals['_USER']._serialized_start=227
  _globals['_USER']._serialized_end=302
  _globals['_USERMESSAGES']._serialized_start=304
  _globals['_USERMESSAGES']._serialized_end=339
  _globals['_USERFOLLOWING']._serialized_start=341
  _globals['_USERFOLLOWING']._serialized_end=380
  _globals['_USERFOLLOWERS']._serialized_start=382
  _globals['_USERFOLLOWERS']._serialized_end=421
# @@protoc_insertion_point(module_scope)
