# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/proto/social_graph.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server/proto/social_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fserver/proto/social_graph.proto\x12\x06tweety\"F\n\rFollowRequest\x12\x19\n\x11\x66ollower_username\x18\x01 \x01(\t\x12\x1a\n\x12\x66ollowing_username\x18\x02 \x01(\t\"2\n\x0e\x46ollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x0fUnfollowRequest\x12\x19\n\x11\x66ollower_username\x18\x01 \x01(\t\x12\x1a\n\x12\x66ollowing_username\x18\x02 \x01(\t\"4\n\x10UnfollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x10\x46ollowersRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x11\x46ollowersResponse\x12\x11\n\tfollowers\x18\x01 \x03(\t\"$\n\x10\x46ollowingRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x11\x46ollowingResponse\x12\x11\n\tfollowing\x18\x01 \x03(\t2\x96\x02\n\x12SocialGraphService\x12\x37\n\x06\x46ollow\x12\x15.tweety.FollowRequest\x1a\x16.tweety.FollowResponse\x12=\n\x08Unfollow\x12\x17.tweety.UnfollowRequest\x1a\x18.tweety.UnfollowResponse\x12\x43\n\x0cGetFollowers\x12\x18.tweety.FollowersRequest\x1a\x19.tweety.FollowersResponse\x12\x43\n\x0cGetFollowing\x12\x18.tweety.FollowingRequest\x1a\x19.tweety.FollowingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.proto.social_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLLOWREQUEST']._serialized_start=43
  _globals['_FOLLOWREQUEST']._serialized_end=113
  _globals['_FOLLOWRESPONSE']._serialized_start=115
  _globals['_FOLLOWRESPONSE']._serialized_end=165
  _globals['_UNFOLLOWREQUEST']._serialized_start=167
  _globals['_UNFOLLOWREQUEST']._serialized_end=239
  _globals['_UNFOLLOWRESPONSE']._serialized_start=241
  _globals['_UNFOLLOWRESPONSE']._serialized_end=293
  _globals['_FOLLOWERSREQUEST']._serialized_start=295
  _globals['_FOLLOWERSREQUEST']._serialized_end=331
  _globals['_FOLLOWERSRESPONSE']._serialized_start=333
  _globals['_FOLLOWERSRESPONSE']._serialized_end=371
  _globals['_FOLLOWINGREQUEST']._serialized_start=373
  _globals['_FOLLOWINGREQUEST']._serialized_end=409
  _globals['_FOLLOWINGRESPONSE']._serialized_start=411
  _globals['_FOLLOWINGRESPONSE']._serialized_end=449
  _globals['_SOCIALGRAPHSERVICE']._serialized_start=452
  _globals['_SOCIALGRAPHSERVICE']._serialized_end=730
# @@protoc_insertion_point(module_scope)
