FIND_ID_PREDECESSOR = 1
FIND_ID_SUCCESSOR = 2
GET_PREDECESSOR = 3
GET_SUCCESSOR = 4
CLOSEST_PRECEDING_FINGER = 5
NOTIFY = 6
GET_SUCCESSOR_AND_NOTIFY = 7
PING = 8
PING_LEADER = 9
ELECTION = 10
SET_PARTITION = 11
RESOLVE_DATA = 12
RETRIEVE_KEY = 13
STORE_KEY = 14
DELETE_KEY = 15

FALSE = 0
TRUE = 1

ALIVE = 'Vivo'
DEAD = 'Muelto'
ARE_YOU = 'Tu ere un nodo?'
YES_IM = 'Soy un nodo, confia'
EMPTY = ''

DISCOVER_AND_JOIN_FREQ = 20
CHECK_LEADER_FREQ = 10
CHECK_FOR_ELECTION_FREQ = 60
FIX_FINGERS_FREQ = 5
CHORD_THREADS_GENERAL_DELAY = 6
FIRST_DISCOVER_AND_JOIN_DELAY = 15
STABILIZE_FREQ = 10
CHECK_PREDECESSOR_FREQ = 10
CHECK_SUCCESSOR_FREQ = 10
FIX_SUCCESSORS_FREQ = 15
FIX_STORAGE_FREQ = 10