FIND_ID_PREDECESSOR = 1
FIND_ID_SUCCESSOR = 2
GET_PREDECESSOR = 3
GET_SUCCESSOR = 4
CLOSEST_PRECEDING_FINGER = 5
NOTIFY = 6
GET_SUCCESSOR_AND_NOTIFY = 7
PING = 8
PING_LEADER = 9
ELECTION = 10

FALSE = 0
TRUE = 1

ALIVE = 'Vivo'
DEAD = 'Muelto'