# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import models_pb2 as models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06tweety\x1a\x0cmodels.proto\"%\n\x12GetMessagesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"8\n\x13GetMessagesResponse\x12!\n\x08messages\x18\x01 \x03(\x0b\x32\x0f.tweety.Message\"6\n\x12PostMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"7\n\x13PostMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x14RepostMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1b\n\x13original_message_id\x18\x02 \x01(\t\"9\n\x15RepostMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xee\x01\n\x0eMessageService\x12\x46\n\x0bPostMessage\x12\x1a.tweety.PostMessageRequest\x1a\x1b.tweety.PostMessageResponse\x12\x46\n\x0bGetMessages\x12\x1a.tweety.GetMessagesRequest\x1a\x1b.tweety.GetMessagesResponse\x12L\n\rRepostMessage\x12\x1c.tweety.RepostMessageRequest\x1a\x1d.tweety.RepostMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMESSAGESREQUEST']._serialized_start=39
  _globals['_GETMESSAGESREQUEST']._serialized_end=76
  _globals['_GETMESSAGESRESPONSE']._serialized_start=78
  _globals['_GETMESSAGESRESPONSE']._serialized_end=134
  _globals['_POSTMESSAGEREQUEST']._serialized_start=136
  _globals['_POSTMESSAGEREQUEST']._serialized_end=190
  _globals['_POSTMESSAGERESPONSE']._serialized_start=192
  _globals['_POSTMESSAGERESPONSE']._serialized_end=247
  _globals['_REPOSTMESSAGEREQUEST']._serialized_start=249
  _globals['_REPOSTMESSAGEREQUEST']._serialized_end=317
  _globals['_REPOSTMESSAGERESPONSE']._serialized_start=319
  _globals['_REPOSTMESSAGERESPONSE']._serialized_end=376
  _globals['_MESSAGESERVICE']._serialized_start=379
  _globals['_MESSAGESERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
