# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social_graph.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'social_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12social_graph.proto\x12\x06tweety\"9\n\rFollowRequest\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ollowed_id\x18\x02 \x01(\t\"2\n\x0e\x46ollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x0fUnfollowRequest\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ollowed_id\x18\x02 \x01(\t\"4\n\x10UnfollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x13GetFollowingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\".\n\x14GetFollowingResponse\x12\x16\n\x0e\x66ollowing_list\x18\x01 \x03(\t\"&\n\x13GetFollowersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\".\n\x14GetFollowersResponse\x12\x16\n\x0e\x66ollowers_list\x18\x01 \x03(\t2\xa2\x02\n\x12SocialGraphService\x12\x37\n\x06\x46ollow\x12\x15.tweety.FollowRequest\x1a\x16.tweety.FollowResponse\x12=\n\x08Unfollow\x12\x17.tweety.UnfollowRequest\x1a\x18.tweety.UnfollowResponse\x12I\n\x0cGetFollowing\x12\x1b.tweety.GetFollowingRequest\x1a\x1c.tweety.GetFollowingResponse\x12I\n\x0cGetFollowers\x12\x1b.tweety.GetFollowersRequest\x1a\x1c.tweety.GetFollowersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLLOWREQUEST']._serialized_start=30
  _globals['_FOLLOWREQUEST']._serialized_end=87
  _globals['_FOLLOWRESPONSE']._serialized_start=89
  _globals['_FOLLOWRESPONSE']._serialized_end=139
  _globals['_UNFOLLOWREQUEST']._serialized_start=141
  _globals['_UNFOLLOWREQUEST']._serialized_end=200
  _globals['_UNFOLLOWRESPONSE']._serialized_start=202
  _globals['_UNFOLLOWRESPONSE']._serialized_end=254
  _globals['_GETFOLLOWINGREQUEST']._serialized_start=256
  _globals['_GETFOLLOWINGREQUEST']._serialized_end=294
  _globals['_GETFOLLOWINGRESPONSE']._serialized_start=296
  _globals['_GETFOLLOWINGRESPONSE']._serialized_end=342
  _globals['_GETFOLLOWERSREQUEST']._serialized_start=344
  _globals['_GETFOLLOWERSREQUEST']._serialized_end=382
  _globals['_GETFOLLOWERSRESPONSE']._serialized_start=384
  _globals['_GETFOLLOWERSRESPONSE']._serialized_end=430
  _globals['_SOCIALGRAPHSERVICE']._serialized_start=433
  _globals['_SOCIALGRAPHSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
